# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "Gemfile", "Gemfile.lock"] # files to exclude
highlighter: true
github:
  is_user_page: true
  is_project_page: false
  owner_url: "https://github.com/qifun"
  owner_gravatar_url: "https://github.com/qifun.png"
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 岂凡技术小站

title: 岂凡技术小站
description: 做真正有趣的游戏<br/>向所有玩家传播快乐
bitbucket: qforce
email: yangbo@qifun.com

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
encoding: utf-8
timezone: CN
permalink: /:year/:month/:day/:title
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

baseurl: ""
