# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "Gemfile", "Gemfile.lock"] # files to exclude
pygments: true
github:
  is_user_page: true
  is_project_page: false
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 岂凡技术小站

title: 岂凡技术小站
description: 做真正有趣的游戏<br/>向所有玩家传播快乐
author:
  name: 杨博
  email: yangbo@qifun.com
  github: qifun
  twitter:
  pinterest:
  linkedin:
  bio: 岂凡 游戏架构师
  email_md5: 50993397b1b5ed2eae8e50e25d9663e8

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
encoding: utf-8
timezone: CN

BASE_PATH:
